version: "3.1"
services:
  frontend:
    restart: always
    expose:
      - 3000
    build: ./frontend
    volumes:
      - ./frontend:/frontend
  backend:
    restart: always
    build: ./backend
    volumes:
      - static_volume:/home/app/backend/staticfiles
      - ./backend:/backend
    expose:
      - 8000
    env_file:
      - ./backend/backend/.env.prod
  nginx:
    build: ./nginx
    ports:
      - 8123:80
    volumes:
      - static_volume:/home/app/backend/staticfiles
    depends_on:
      - backend
      - frontend

volumes:
  static_volume:
