version: "3.1"
services:
  app:
    restart: always
    build: .  # . is current directory
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8010"
    volumes:
      - .:/code
    ports:
      - "8010:8010"