version: "3.1"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_PASSWORD=example
  app:
    restart: always
    build: .  # . is current directory
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8010"
    volumes:
      - .:/code
    ports:
      - "8010:8010"
    environment:
      - ENGINE=django.db.backends.postgresql
      - NAME=postgres
      - USER=postgres
      - PASSWORD=example
      - HOST=db
      - PORT=5432
    depends_on:
      - db