# Generated by Django 4.0.3 on 2022-03-12 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan_of_action', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='plan_of_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='plan_of_action.planofaction'),
        ),
    ]
