# Generated by Django 4.0.2 on 2022-02-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs261', '0002_alter_userprofile_business_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='years_experience',
            field=models.SmallIntegerField(null=True),
        ),
    ]
