# Generated by Django 4.0.3 on 2022-03-13 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsessionrequestedskill',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_skills', to='group_session.groupsessionrequest'),
        ),
    ]
