# Generated by Django 4.0.3 on 2022-03-12 17:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
        ('plan_of_action', '0002_alter_comment_plan_of_action'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('alternative_proposed', 'Alternative Proposed'), ('accepted', 'Accepted')], default='requested', max_length=30)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('mentoring_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='matching.mentoringpair')),
                ('plans_of_action', models.ManyToManyField(blank=True, related_name='discussed_in', to='plan_of_action.planofaction')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('description', models.TextField()),
                ('attachments', django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to='meeting_files/'), default=list, size=None)),
                ('approved', models.BooleanField(default=False)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='meeting.meeting')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
