# Generated by Django 4.0.2 on 2022-02-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_years_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessArea',
        ),
    ]
