# Generated by Django 4.0.2 on 2022-03-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_businessarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.CharField(choices=[('anlst', 'title.anlst'), ('assoc', 'title.assoc'), ('avp', 'title.avp'), ('vp', 'title.vp'), ('dir', 'title.dir'), ('md', 'title.md')], max_length=5, null=True),
        ),
    ]
