# Generated by Django 4.0.3 on 2022-03-11 10:23

import django.contrib.postgres.fields
from django.db import migrations, models
import language.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2, validators=[language.utils.is_valid_language]), default=['en'], size=None),
            preserve_default=False,
        ),
    ]
