# Generated by Django 4.0.3 on 2022-03-11 21:12

import django.contrib.postgres.fields
from django.db import migrations, models
import language.utils
import skill.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userprofile_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2, validators=[language.utils.is_valid_language]), default=list(), size=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512, validators=[skill.utils.validate_skill]), default=list(), size=None),
        ),
    ]
