name: Test, build, and deploy frontend project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js version 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Load Yarn Cache 
      uses: actions/cache@v1
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install frontend dependencies
      run: |
        cd frontend
        yarn --prefer-offline
    - name: Run tests with Jest
      run: |
        cd frontend
        yarn test --outputFile=report.json --ci --coverage --coverageReporters=\"text\" --coverageReporters=\"text-summary\" --watchAll=false --json
    - name: Check frontend code coverage
      uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        threshold: 90 # Require at least 90% code coverage
        annotations: none
        skip-step: all
        coverage-file: ./frontend/report.json
        base-coverage-file: ./frontend/report.json
    # Recheckout to current branch since the previous action checks out to main branch
    - uses: actions/checkout@v2
    - name: Build website
      run: |
        cd frontend
        yarn --prefer-offline
        yarn build
      env:
        REACT_APP_API_HOST: ${{ secrets.API_HOST }}
    - name: Deploy to Firebase Hosting (Preview)
      uses: FirebaseExtended/action-hosting-deploy@v0
      if: ${{ github.event_name == 'pull_request' }}
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        projectId: '${{ env.PROJECT_ID }}'
        expires: 7d
        entryPoint: frontend
    - name: Deploy to Firebase Hosting (Main)
      uses: FirebaseExtended/action-hosting-deploy@v0
      if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
        projectId: '${{ env.PROJECT_ID }}'
        channelId: live
        entryPoint: frontend
