name: Test and build application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Set up Node.js version 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install frontend dependencies
      run: |
        cd frontend
        yarn
    - name: Run tests with Jest
      run: |
        cd frontend
        yarn test
    - name: Check frontend code coverage
      uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        threshold: 90 # Require at least 90% code coverage
        working-directory: 'frontend'
        annotations: none
        skip-step: install
        test-script: "yarn test --silent --ci --coverage --coverageReporters=\"text\" --coverageReporters=\"text-summary\" --watchAll=false"
    - name: Check backend code coverage
      uses: dc740/django-coveragepy-github-action@0.9
      with:
        django-app: '***REMOVED***'
        minimum-coverage: '90'
