name: Test backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Run test and generate coverage results
      run: |
        cd backend
        python -m pip install --upgrade pipenv wheel
        pipenv install --deploy --dev
        pipenv run coverage run --source='.' manage.py test
        pipenv run coverage xml
    - name: Generate coverage report and check
      uses: orgoro/coverage@v2.1
      with:
        coverageFile: ./backend/coverage.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        thresholdAll: 0.9
  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js version 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install frontend dependencies
      run: |
        cd frontend
        yarn
    - name: Run tests with Jest
      run: |
        cd frontend
        yarn test
    - name: Check frontend code coverage
      uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        threshold: 90 # Require at least 90% code coverage
        working-directory: 'frontend'
        annotations: none
        skip-step: install
        test-script: "yarn test --silent --ci --coverage --coverageReporters=\"text\" --coverageReporters=\"text-summary\" --watchAll=false"
    - name: Build frontend project
      run: |
        cd frontend
        yarn build
