name: Test backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Check backend code coverage
      uses: dc740/django-coveragepy-github-action@0.9
      working-directory: ./backend
      with:
        django-app: 'dbcampus'
        minimum-coverage: '90'
