name: Test backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Run test and generate coverage results
      working-directory: backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        coverage run --source='.' manage.py test
        coverage xml
    - name: Generate coverage report and check
      uses: orgoro/coverage@v2.1
      with:
        coverageFile: ./backend/coverage.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        thresholdAll: 0.9
