# Generated by Django 4.0.2 on 2022-02-12 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_userfeedback_type_alter_userfeedbackreply_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedbackreply',
            name='feedback',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='feedback.userfeedback'),
        ),
    ]
