# Generated by Django 4.0.2 on 2022-02-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_userfeedbackreply_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfeedbackreply',
            options={'get_latest_by': 'modified'},
        ),
        migrations.RemoveField(
            model_name='userfeedbackreply',
            name='deleted',
        ),
    ]
