# Generated by Django 4.0.2 on 2022-03-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_userfeedbackreply_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
